# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 6
numero = int(input("insira um numero: "))
contador = 2

while contador <= numero:
  print(contador)
  contador += 2