# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 9
soma = 0
contador = int(input("digite um numero (0 encerra): "))
while contador  == 0:
 soma += contador
 contador = int(input("gigite um numero (0 encerra): "))
print(f"a soma dos numeros e {soma}")