# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 2
nome =input("digite seu nome:")
senha =input("digite sua senha:")

while nome == senha:
  print("erro")
  nome =input("digite seu nome:")
  senha =input("digite sua senha:")

print("sucesso")