# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 7

numero = int(input("por favor, digite um numero: "))

contador = 1
while contador <= 10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador += 1