# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 10

maiornumero = 0
numero = int(input("digite um numero: "))
while numero >= 0:
  numero = int(input("digite um numero negativo: "))
if numero > maiornumero:
  maiornumero = numero
print(f"o maior numero è {maiornumero}")