# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7wdn8xQNmo-kPIx3TuffXgfc-vdYMA6
"""

#exercicio 8
nome = str(input("insira nome de usuario: "))
senha = str(input("digite senha: "))
while senha == nome:
  print("erro, insira novamente o nome e a senha: ")
  break